Repository CloudNationHQ/terraform-azure-pe, pull requests merged in 2024-10, with the labels that each got.

#15 feat: auto generated docs and refine makefile
  Makefile
  README.md
  tests/deploy_test.go
Labels: documentation

#17 fix: fixed manual connection property in private service connection
  main.tf
Labels: bug

#19 fix: add request message parameter to private service connection
  main.tf
Labels: enhancement

#21 fix: fix locals to include request message
  locals.tf
Labels: bug, enhancement
